export const seedProducts = [
  {
    name: "Laptop Gamer Pro",
    category: "Ordinateurs",
    price: 1500,
    image: "/products/product-laptop.jpg",
    description: 'Puissant laptop pour gaming et travail, écran 15.6" haute résolution, RTX 4070.',
    stock: 10,
  },
  {
    name: "Laptop Ultrabook",
    category: "Ordinateurs",
    price: 1100,
    image: "/products/product-laptop.jpg",
    description: "Ultrabook léger et performant, idéal pour les professionnels en déplacement.",
    stock: 15,
  },
  {
    name: 'Moniteur 4K 27"',
    category: "Ordinateurs",
    price: 450,
    image: "/products/product-monitor.jpg",
    description: "Écran 4K UHD 27 pouces, couleurs précises pour le design et la photo.",
    stock: 12,
  },
  {
    name: 'Moniteur Curved 32"',
    category: "Ordinateurs",
    price: 650,
    image: "/products/product-monitor.jpg",
    description: "Écran incurvé 32 pouces QHD 165Hz, parfait pour le gaming immersif.",
    stock: 8,
  },
  {
    name: "Smartphone Pro",
    category: "Smartphones & Tablettes",
    price: 900,
    image: "/products/product-phone.jpg",
    description: "Smartphone haut de gamme avec caméra 108MP et batterie longue durée.",
    stock: 20,
  },
  {
    name: "Smartphone Lite",
    category: "Smartphones & Tablettes",
    price: 350,
    image: "/products/product-phone.jpg",
    description: "Smartphone abordable avec un bel écran AMOLED et double caméra.",
    stock: 35,
  },
  {
    name: 'Tablette 10"',
    category: "Smartphones & Tablettes",
    price: 500,
    image: "/products/product-tablet.jpg",
    description: "Tablette 10 pouces idéale pour le divertissement et la productivité.",
    stock: 18,
  },
  {
    name: 'Tablette Pro 12"',
    category: "Smartphones & Tablettes",
    price: 850,
    image: "/products/product-tablet.jpg",
    description: "Tablette professionnelle 12 pouces avec stylet et clavier inclus.",
    stock: 10,
  },
  {
    name: "Casque Audio Premium",
    category: "Audio",
    price: 120,
    image: "/products/product-headphones.jpg",
    description: "Casque sans fil avec réduction de bruit active et son Hi-Fi.",
    stock: 30,
  },
  {
    name: "Enceinte Bluetooth",
    category: "Audio",
    price: 80,
    image: "/products/product-speaker.jpg",
    description: "Enceinte portable Bluetooth 5.0 avec basses profondes, étanche IPX7.",
    stock: 40,
  },
  {
    name: "Écouteurs Sans Fil",
    category: "Audio",
    price: 65,
    image: "/products/product-earbuds.jpg",
    description: "Écouteurs true wireless avec ANC, 30h d'autonomie avec le boîtier.",
    stock: 50,
  },
  {
    name: "Enceinte Home Cinema",
    category: "Audio",
    price: 250,
    image: "/products/product-speaker.jpg",
    description: "Barre de son surround avec caisson de basses sans fil, Dolby Atmos.",
    stock: 12,
  },
  {
    name: "Appareil Photo Hybride",
    category: "Photo & Vidéo",
    price: 980,
    image: "/products/product-camera.jpg",
    description: "Appareil photo hybride 24MP, vidéo 4K, stabilisation 5 axes.",
    stock: 8,
  },
  {
    name: "Smartwatch Sport",
    category: "Photo & Vidéo",
    price: 250,
    image: "/products/product-smartwatch.jpg",
    description: "Montre connectée avec GPS, suivi cardiaque et 7 jours d'autonomie.",
    stock: 25,
  },
  {
    name: "Caméra Action 4K",
    category: "Photo & Vidéo",
    price: 320,
    image: "/products/product-camera.jpg",
    description: "Caméra d'action 4K 60fps, étanche 10m, stabilisation électronique.",
    stock: 20,
  },
  {
    name: "Clavier Mécanique",
    category: "Accessoires",
    price: 95,
    image: "/products/product-keyboard.jpg",
    description: "Clavier mécanique compact sans fil, switches tactiles, rétroéclairage RGB.",
    stock: 35,
  },
  {
    name: "Souris Sans Fil",
    category: "Accessoires",
    price: 55,
    image: "/products/product-mouse.jpg",
    description: "Souris ergonomique sans fil, capteur 16000 DPI, 70h d'autonomie.",
    stock: 45,
  },
  {
    name: "Batterie Externe 20000mAh",
    category: "Accessoires",
    price: 40,
    image: "/products/product-powerbank.jpg",
    description: "Power bank compacte avec charge rapide USB-C et double sortie.",
    stock: 60,
  },
  {
    name: "Sacoche Laptop Cuir",
    category: "Accessoires",
    price: 85,
    image: "/products/product-bag.jpg",
    description: 'Sacoche en cuir véritable pour laptop jusqu\'à 15", compartiments multiples.',
    stock: 20,
  },
  {
    name: "Lampe de Bureau LED",
    category: "Bureau",
    price: 65,
    image: "/products/product-lamp.jpg",
    description: "Lampe articulée LED avec 5 niveaux de luminosité et port USB intégré.",
    stock: 30,
  },
  {
    name: "Sac à Dos Tech",
    category: "Bureau",
    price: 110,
    image: "/products/product-bag.jpg",
    description: "Sac à dos antivol avec compartiment laptop, port USB et imperméable.",
    stock: 25,
  },
  {
    name: "Clavier Ergonomique",
    category: "Bureau",
    price: 130,
    image: "/products/product-keyboard.jpg",
    description: "Clavier ergonomique split avec repose-poignets, idéal pour le bureau.",
    stock: 15,
  },
];

